In [51]:
import pandas as pd
import numpy as np

In [8]:
dates_1 = pd.Series(['2021-01-01', '2021-01-02', '2021-02-01'])
dates_2 = pd.Series(['2021-01-01-10:01:01', '2021-01-02-10:01:02', '2021-02-01-10:01:01'])
dates_3 = pd.Series(['01/01/2021', '02/01/2021', '03/01/2021', '11/01/2021'])

In [3]:
pd.to_datetime(dates_1)

0   2021-01-01
1   2021-01-02
2   2021-02-01
dtype: datetime64[us]

In [4]:
pd.to_datetime(dates_2)

0   2021-01-01 10:01:01
1   2021-01-02 10:01:02
2   2021-02-01 10:01:01
dtype: datetime64[us]

In [9]:
pd.to_datetime(dates_3)

0   2021-01-01
1   2021-02-01
2   2021-03-01
3   2021-11-01
dtype: datetime64[us]

In [14]:
pd.to_datetime(dates_3, format='%d/%m/%Y')

0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-11
dtype: datetime64[us]

In [17]:
dates_3 = pd.to_datetime(dates_3, format='%d/%m/%Y')

In [18]:
dates_3

0   2021-01-01
1   2021-01-02
2   2021-01-03
3   2021-01-11
dtype: datetime64[us]

In [20]:
dates_3 + pd.Timedelta("1 day")

0   2021-01-02
1   2021-01-03
2   2021-01-04
3   2021-01-12
dtype: datetime64[us]

In [21]:
dates_3> '2021-01-01'

0    False
1     True
2     True
3     True
dtype: bool

In [27]:
pd.to_datetime(dates_2)

0   2021-01-01 10:01:01
1   2021-01-02 10:01:02
2   2021-02-01 10:01:01
dtype: datetime64[us]

In [31]:
df_dates = pd.DataFrame({'date': dates_2})
df_dates['date'] = pd.to_datetime(df_dates['date'])

In [32]:
df_dates['ano'] = df_dates['date'].dt.year
df_dates['mes'] = df_dates['date'].dt.month
df_dates['dia'] = df_dates['date'].dt.day
df_dates['hora'] = df_dates['date'].dt.hour
df_dates['semana'] = df_dates['date'].dt.isocalendar().week
df_dates['is_ano_bisexto'] = df_dates['date'].dt.is_leap_year
df_dates['dia_semana'] = df_dates['date'].dt.weekday
df_dates['trimestre'] = df_dates['date'].dt.quarter
df_dates['dia_ano'] = df_dates['date'].dt.dayofyear

In [36]:
df_dates

,date,ano,mes,dia,hora,semana,is_ano_bisexto,dia_semana,trimestre,dia_ano
0,2021-01-01 10:01:01,2021,1,1,10,53,False,4,1,1
1,2021-01-02 10:01:02,2021,1,2,10,53,False,5,1,2
2,2021-02-01 10:01:01,2021,2,1,10,5,False,0,1,32

In [38]:
pd.date_range(start='2022-01-01', end='2022-06-01')

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2022-05-23', '2022-05-24', '2022-05-25', '2022-05-26',
               '2022-05-27', '2022-05-28', '2022-05-29', '2022-05-30',
               '2022-05-31', '2022-06-01'],
              dtype='datetime64[us]', length=152, freq='D')

In [44]:
pd.date_range(start='2022-01-01', end='2022-06-01', freq='h')

DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 01:00:00',
               '2022-01-01 02:00:00', '2022-01-01 03:00:00',
               '2022-01-01 04:00:00', '2022-01-01 05:00:00',
               '2022-01-01 06:00:00', '2022-01-01 07:00:00',
               '2022-01-01 08:00:00', '2022-01-01 09:00:00',
               ...
               '2022-05-31 15:00:00', '2022-05-31 16:00:00',
               '2022-05-31 17:00:00', '2022-05-31 18:00:00',
               '2022-05-31 19:00:00', '2022-05-31 20:00:00',
               '2022-05-31 21:00:00', '2022-05-31 22:00:00',
               '2022-05-31 23:00:00', '2022-06-01 00:00:00'],
              dtype='datetime64[us]', length=3625, freq='h')

In [46]:
pd.date_range(start='2022-01-01', end='2022-06-01', freq='ME')

DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31'],
              dtype='datetime64[us]', freq='ME')

In [48]:
pd.date_range(start='2022-01-01', end='2022-06-01', freq='5h')

DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 05:00:00',
               '2022-01-01 10:00:00', '2022-01-01 15:00:00',
               '2022-01-01 20:00:00', '2022-01-02 01:00:00',
               '2022-01-02 06:00:00', '2022-01-02 11:00:00',
               '2022-01-02 16:00:00', '2022-01-02 21:00:00',
               ...
               '2022-05-29 23:00:00', '2022-05-30 04:00:00',
               '2022-05-30 09:00:00', '2022-05-30 14:00:00',
               '2022-05-30 19:00:00', '2022-05-31 00:00:00',
               '2022-05-31 05:00:00', '2022-05-31 10:00:00',
               '2022-05-31 15:00:00', '2022-05-31 20:00:00'],
              dtype='datetime64[us]', length=725, freq='5h')

In [49]:
pd.date_range(start='2022-01-01', end='2022-06-01', freq='B')

DatetimeIndex(['2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06',
               '2022-01-07', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14',
               ...
               '2022-05-19', '2022-05-20', '2022-05-23', '2022-05-24',
               '2022-05-25', '2022-05-26', '2022-05-27', '2022-05-30',
               '2022-05-31', '2022-06-01'],
              dtype='datetime64[us]', length=108, freq='B')

In [52]:
dates = pd.date_range(start='2022-01-01', end='2022-06-01', freq='D')
df = pd.DataFrame({'date': pd.date_range(start='2022-01-01', end='2022-06-01', freq='D'),
                 'values': np.random.normal(loc=0.0, scale=1.0, size=dates.shape[0])})
df.set_index('date', inplace=True)
df.head(8)

              values
date
2022-01-01  0.557212
2022-01-02  0.916942
2022-01-03 -0.877868
2022-01-04  0.272164
2022-01-05 -1.677370
2022-01-06 -1.759153
2022-01-07  0.763016
2022-01-08  0.485230

In [53]:
df.resample('W').sum() # sum, mean, max, min

              values
date
2022-01-02  1.474153
2022-01-09 -2.056517
2022-01-16  2.609535
2022-01-23 -4.420487
2022-01-30  3.262006
2022-02-06 -3.338164
2022-02-13 -3.704318
2022-02-20  1.813463
2022-02-27 -2.227136
2022-03-06  3.216317
2022-03-13  3.756685
2022-03-20 -0.584128
2022-03-27 -1.350436
2022-04-03 -4.362609
2022-04-10  0.959701
2022-04-17  1.576124
2022-04-24 -0.208466
2022-05-01  1.243813
2022-05-08  2.274669
2022-05-15 -3.428909
2022-05-22  0.539413
2022-05-29  1.055302
2022-06-05 -0.633537

In [56]:
df.resample('ME').sum() # sum, mean, max, min

              values
date
2022-01-31  0.777312
2022-02-28 -5.042672
2022-03-31  1.803799
2022-04-30 -1.034468
2022-05-31  1.157462
2022-06-30 -0.194960

In [ ]:
df_itausa = pd.read_csv('itausa.csv') # serie do yahoo finance, aparentemente sem valores ausentes
df_itausa['Date'] = pd.to_datetime(df_itausa['Date'])
df_itausa.set_index('Date', inplace=True)

dates = pd.date_range(start='2000-01-03', end='2022-02-17', freq='B')
dates = pd.DataFrame({'Date':dates}).set_index('Date')
df_itausa = dates.join(df_itausa, how='left')

df_itausa[df_itausa['Close'].isna()]